kind: pipeline
name: DPutils test

steps:
  - name: stepOne
    image: haskell
    commands:
      - ls
      - which cabal
      - ls -alh /root/.cabal/store
      - ls -alh /root/.cabal/packages
      - cabal update
      - cabal new-test
      - ls -alh /root/.cabal
      - ls -alh /root/.cabal/store
      - ls -alh /root/.cabal/packages

#pipeline:
#  build:
#    image: plugins/git
#  commands:
#    - which cabal
